let arr = [
    {
        "id": 1,
        "img": "C:/Users/Admin/Desktop/practic/public/601909f6dfa015049615db25.jpg",
        "brand": "Toyota",
        "model": "Camry",
        "price": 2500000,
        "transmission": "АКПП",
        "drive": "передний",
        "body": "седан",
        "fuel": "бензин",
        "engine_volume": 2.5,
        "engine_power": 200,
        "max_speed": 210,
        "number_of_gears": 8,
        "acceleration_0_100": 8.0,
        "trunk_volume": 500,
        "fuel_consumption": 8.5,
        "number_of_cars_in_showroom": 5,
        "year": 2021,
        "color": "чёрный"
    },
    {
        "id": 2,
        "img": "C:/Users/Admin/Desktop/practic/public/maxresdefault.jpg",
        "brand": "Toyota",
        "model": "RAV4",
        "price": 3000000,
        "transmission": "АКПП",
        "drive": "полный",
        "body": "внедорожник",
        "fuel": "бензин",
        "engine_volume": 2.5,
        "engine_power": 203,
        "max_speed": 200,
        "number_of_gears": 8,
        "acceleration_0_100": 8.5,
        "trunk_volume": 580,
        "fuel_consumption": 7.5,
        "number_of_cars_in_showroom": 4,
        "year": 2022,
        "color": "Голубой"
    },
    {
        "id": 3,
        "img": "C:/Users/Admin/Desktop/practic/public/22614427_web1_TSR-2020-Honda-Civic-front-EDH-200905.jpg",
        "brand": "Honda",
        "model": "Civic",
        "price": 2200000,
        "transmission": "МКПП",
        "drive": "передний",
        "body": "хэтчбек",
        "fuel": "бензин",
        "engine_volume": 2.0,
        "engine_power": 158,
        "max_speed": 200,
        "number_of_gears": 6,
        "acceleration_0_100": 7.5,
        "trunk_volume": 400,
        "fuel_consumption": 7.0,
        "number_of_cars_in_showroom": 4,
        "year": 2020,
        "color": "Серый"
    },
    {
        "id": 4,
        "img": "C:/Users/Admin/Desktop/practic/public/9.jpg",
        "brand": "Honda",
        "model": "Accord",
        "price": 2600000,
        "transmission": "АКПП",
        "drive": "передний",
        "body": "седан",
        "fuel": "бензин",
        "engine_volume": 2.4,
        "engine_power": 189,
        "max_speed": 210,
        "number_of_gears": 6,
        "acceleration_0_100": 6.8,
        "trunk_volume": 450,
        "fuel_consumption": 7.5,
        "number_of_cars_in_showroom": 3,
        "year": 2021,
        "color": "серебряный"
    },
    {
        "id": 5,
        "img": "C:/Users/Admin/Desktop/practic/public/Ford_Focus_Mk_IV_Facelift_Auto_Zuerich_2021_IMG_0406.jpg",
        "brand": "Ford",
        "model": "Focus",
        "price": 2100000,
        "transmission": "АКПП",
        "drive": "передний",
        "body": "седан",
        "fuel": "бензин",
        "engine_volume": 1.5,
        "engine_power": 180,
        "max_speed": 195,
        "number_of_gears": 6,
        "acceleration_0_100": 8.5,
        "trunk_volume": 450,
        "fuel_consumption": 6.5,
        "number_of_cars_in_showroom": 3,
        "year": 2021,
        "color": "голубой"
    },
    {
        "id": 6,
        "img": "C:/Users/Admin/Desktop/practic/public/bbrg5u12bp1byct9kjdnsencckpnm71t.jpg",
        "brand": "Ford",
        "model": "Escape",
        "price": 2800000,
        "transmission": "AКПП",
        "drive": "полный",
        "body": "внедорожник",
        "fuel": "бензин",
        "engine_volume": 2.5,
        "engine_power": 190,
        "max_speed": 200,
        "number_of_gears": 8,
        "acceleration_0_100": 7.5,
        "trunk_volume": 600,
        "fuel_consumption": 8.0,
        "number_of_cars_in_showroom": 3,
        "year": 2022,
        "color": "зеленый"
    },
    {
        "id": 7,
        "img": "C:/Users/Admin/Desktop/practic/public/2-BMW-3-Series.jpg",
        "brand": "BMW",
        "model": "3 Series",
        "price": 3500000,
        "transmission": "АКПП",
        "drive": "задний",
        "body": "седан",
        "fuel": "бензин",
        "engine_volume": 2.0,
        "engine_power": 250,
        "max_speed": 250,
        "number_of_gears": 8,
        "acceleration_0_100": 5.8,
        "trunk_volume": 480,
        "fuel_consumption": 7.5,
        "number_of_cars_in_showroom": 2,
        "year": 2022,
        "color": "серый"
    },
    {
        "id": 8,
        "img": "C:/Users/Admin/Desktop/practic/public/audi-a4-faelift-2021.jpg",
        "brand": "Audi",
        "model": "A4",
        "price": 3300000,
        "transmission": "АКПП",
        "drive": "полный",
        "body": "седан",
        "fuel": "бензин",
        "engine_volume": 2.0,
        "engine_power": 245,
        "max_speed": 240,
        "number_of_gears": 7,
        "acceleration_0_100": 6.5,
        "trunk_volume": 480,
        "fuel_consumption": 6.8,
        "number_of_cars_in_showroom": 3,
        "year": 2021,
        "color": "серебряный"
    },
    {
        "id": 9,
        "img": "C:/Users/Admin/Desktop/practic/public/Mercedes_C300D_0000.jpg",
        "brand": "Mercedes-Benz",
        "model": "C-Class",
        "price": 4000000,
        "transmission": "АКПП",
        "drive": "задний",
        "body": "седан",
        "fuel": "бензин",
        "engine_volume": 2.0,
        "engine_power": 255,
        "max_speed": 250,
        "number_of_gears": 9,
        "acceleration_0_100": 5.9,
        "trunk_volume": 480,
        "fuel_consumption": 7.0,
        "number_of_cars_in_showroom": 2,
        "year": 2022,
        "color": "черный"
    },
    {
        "id": 10,
        "img": "C:/Users/Admin/Desktop/practic/public/2019-nissan-altima-102-1538074559.jpg",
        "brand": "Nissan",
        "model": "Altima",
        "price": 2400000,
        "transmission": "АКПП",
        "drive": "передний",
        "body": "седан",
        "fuel": "бензин",
        "engine_volume": 2.5,
        "engine_power": 182,
        "max_speed": 210,
        "number_of_gears": 1,
        "acceleration_0_100": 8.2,
        "trunk_volume": 450,
        "fuel_consumption": 8.0,
        "number_of_cars_in_showroom": 4,
        "year": 2020,
        "color": "белый"
    },
    {
        "id": 11,
        "img": "C:/Users/Admin/Desktop/practic/public/1.jpg",
        "brand": "Hyundai",
        "model": "Sonata",
        "price": 2300000,
        "transmission": "АКПП",
        "drive": "передний",
        "body": "седан",
        "fuel": "бензин",
        "engine_volume": 2.4,
        "engine_power": 185,
        "max_speed": 200,
        "number_of_gears": 6,
        "acceleration_0_100": 8.0,
        "trunk_volume": 450,
        "fuel_consumption": 7.5,
        "number_of_cars_in_showroom": 5,
        "year": 2021,
        "color": "серый"
    },
    {
        "id": 12,
        "img": "C:/Users/Admin/Desktop/practic/public/2020-kia-k5-kdm-spec.jpg",
        "brand": "Kia",
        "model": "Optima",
        "price": 2200000,
        "transmission": "АКПП",
        "drive": "передний",
        "body": "седан",
        "fuel": "бензин",
        "engine_volume": 2.0,
        "engine_power": 147,
        "max_speed": 190,
        "number_of_gears": 6,
        "acceleration_0_100": 9.0,
        "trunk_volume": 450,
        "fuel_consumption": 8.0,
        "number_of_cars_in_showroom": 4,
        "year": 2020,
        "color": "черный"
    },
    {
        "id": 13,
        "img": "C:/Users/Admin/Desktop/practic/public/image-28-04-21-20-15-scaled.jpg",
        "brand": "Volkswagen",
        "model": "Passat",
        "price": 2700000,
        "transmission": "АКПП",
        "drive": "передний",
        "body": "седан",
        "fuel": "бензин",
        "engine_volume": 2.0,
        "engine_power": 174,
        "max_speed": 210,
        "number_of_gears": 6,
        "acceleration_0_100": 7.8,
        "trunk_volume": 586,
        "fuel_consumption": 7.2,
        "number_of_cars_in_showroom": 3,
        "year": 2021,
        "color": "белый"
    },
    {
        "id": 14,
        "img": "C:/Users/Admin/Desktop/practic/public/2021-chevrolet-malibu-mmp-1-1598373352.jpg",
        "brand": "Chevrolet",
        "model": "Malibu",
        "price": 2400000,
        "transmission": "АКПП",
        "drive": "передний",
        "body": "седан",
        "fuel": "бензин",
        "engine_volume": 1.5,
        "engine_power": 160,
        "max_speed": 195,
        "number_of_gears": 6,
        "acceleration_0_100": 8.5,
        "trunk_volume": 450,
        "fuel_consumption": 7.8,
        "number_of_cars_in_showroom": 4,
        "year": 2021,
        "color": "черный"
    },
   {
    "id": 15,
    "img": "C:/Users/Admin/Desktop/practic/public/content3-image-desktop-1200x820.jpg",
    "brand": "Subaru",
    "model": "Outback",
    "price": 3200000,
    "transmission": "CVT",
    "drive": "полный",
    "body": "кроссовер",
    "fuel": "бензин",
    "engine_volume": 2.5,
    "engine_power": 182,
    "max_speed": 210,
    "number_of_gears": 1,
    "acceleration_0_100": 8.5,
    "trunk_volume": 500,
    "fuel_consumption": 8.0,
    "number_of_cars_in_showroom": 3,
    "year": 2022,
    "color": "синий"
},
{
    "id": 16,
    "img": "C:/Users/Admin/Desktop/practic/public/2021-mazda-cx-5_100769178_h.jpg",
    "brand": "Mazda",
    "model": "CX-5",
    "price": 2900000,
    "transmission": "МКПП",
    "drive": "полный",
    "body": "кроссовер",
    "fuel": "бензин",
    "engine_volume": 2.5,
    "engine_power": 187,
    "max_speed": 210,
    "number_of_gears": 6,
    "acceleration_0_100": 7.9,
    "trunk_volume": 506,
    "fuel_consumption": 7.5,
    "number_of_cars_in_showroom": 2,
    "year": 2021,
    "color": "красный"
}

]

export default arr